-- Real persistence.
--
-- The nine seeded meetings stay as a compiled fixture — they are the populated
-- workspace the brief asks for, and regenerating them on every cold start is
-- free. Everything a user *uploads* lands here instead, and from that moment
-- it is a row, not a fixture: the transcript came from Deepgram, the summary
-- came from a model reading that transcript, and the citations point at
-- segment IDs that exist in this table.
--
-- That is the line the first version of this build got wrong. Read paths merge
-- the two sources; write paths only ever touch Postgres.

-- One row per Google account that has signed in. The refresh token is what
-- lets the calendar be read while the user is not on the page.
create table if not exists users (
  id                    text primary key,   -- Google's stable subject id
  email                 text not null,
  name                  text not null default '',
  image                 text,
  google_refresh_token  text,
  calendar_connected    boolean not null default false,
  -- Per-user preferences, Fathom's "auto-record all meetings" line.
  auto_record           text not null default 'all',   -- all | external | none
  created_at            timestamptz not null default now(),
  last_seen_at          timestamptz not null default now()
);

create table if not exists meetings (
  id              text primary key,
  title           text not null,
  kind            text not null default 'planning',
  platform        text not null default 'upload',
  started_at      timestamptz not null default now(),
  duration_ms     integer not null default 0,
  gist            text not null default '',
  -- queued | transcribing | analysing | ready | failed
  status          text not null default 'queued',
  error           text,
  -- Where the audio lives. A Vercel Blob URL for browser-recorded calls, or a
  -- Where an uploaded recording's audio lives: a blob URL, or this app's
  -- present, because it needs no signing round-trip to play.
  media_path      text,
  media_url       text,
  media_mime      text,
  -- Fallback home for the audio when no object store is attached.
  media_bytes     bytea,
  -- How this meeting came to exist: 'call' (tab audio + mic), 'mic',
  -- 'import' (a transcript you brought), 'upload' (a media file).
  origin          text not null default 'import',
  -- Provenance, verbatim: which model transcribed and which analysed.
  transcript_source text,
  -- The thumbnail's waveform, precomputed. Drawing it in the list otherwise
  -- means loading every segment of every call to render the home page.
  shape           jsonb not null default '[]'::jsonb,
  low_confidence_ratio real not null default 0,
  -- Whose workspace this meeting belongs to. Every read filters on it.
  owner_id        text,
  -- Set when this row came from the sample workspace, so it can be told
  -- apart from a real recording and removed in one go.
  sample          boolean not null default false,
  created_at      timestamptz not null default now()
);
create index if not exists meetings_owner on meetings(owner_id, started_at desc);

-- Speakers are per meeting, not global: an uploaded file has whatever voices
-- the diarizer found, and the user renames them afterwards. "Speaker 0" is a
-- real state this product has to handle well, which the seeded cast never
-- exercises.
create table if not exists speakers (
  id              text primary key,
  meeting_id      text not null references meetings(id) on delete cascade,
  -- Deepgram's integer speaker label.
  diarization_id  integer not null,
  name            text not null,
  hue             integer not null default 0,
  talk_ms         integer not null default 0,
  word_count      integer not null default 0,
  is_external     boolean not null default false,
  -- A stable identity across meetings, when one is known. The sample
  -- workspace sets it so the same person is one person on the action board
  -- and in the commitment tracker; a diarized recording leaves it null
  -- until someone names the voice.
  person_key      text,
  title           text,
  company         text,
  email           text
);
create index if not exists speakers_meeting on speakers(meeting_id);

create table if not exists segments (
  id              text primary key,
  meeting_id      text not null references meetings(id) on delete cascade,
  speaker_id      text not null,
  start_ms        integer not null,
  end_ms          integer not null,
  text            text not null,
  confidence      real not null default 1,
  crosstalk       boolean not null default false,
  idx             integer not null
);
create index if not exists segments_meeting_idx on segments(meeting_id, idx);
create index if not exists segments_meeting_start on segments(meeting_id, start_ms);

-- Full-text search over real transcripts, generated by Postgres rather than
-- computed in JS on every request.
alter table segments
  add column if not exists tsv tsvector
  generated always as (to_tsvector('english', text)) stored;
create index if not exists segments_tsv on segments using gin(tsv);

create table if not exists chapters (
  id              text primary key,
  meeting_id      text not null references meetings(id) on delete cascade,
  start_ms        integer not null,
  end_ms          integer not null,
  title           text not null,
  gist            text not null default '',
  idx             integer not null
);
create index if not exists chapters_meeting on chapters(meeting_id, idx);

create table if not exists summaries (
  id              text primary key,
  meeting_id      text not null references meetings(id) on delete cascade,
  template_key    text not null,
  generated_at    timestamptz not null default now(),
  -- The model that wrote it, so a switch is visible in the data too.
  model           text
);
create index if not exists summaries_meeting on summaries(meeting_id);

create table if not exists summary_sections (
  id              text primary key,
  summary_id      text not null references summaries(id) on delete cascade,
  heading         text not null,
  idx             integer not null
);

-- The whole point: a bullet is a row with its own anchor, and that anchor is
-- a FK to a segment that actually exists. A citation that cannot be resolved
-- is a broken row, not a dead hyperlink.
create table if not exists summary_bullets (
  id              text primary key,
  section_id      text not null references summary_sections(id) on delete cascade,
  text            text not null,
  anchor_ms       integer not null,
  segment_id      text,
  speaker_id      text,
  idx             integer not null
);
create index if not exists bullets_section on summary_bullets(section_id, idx);

create table if not exists action_items (
  id              text primary key,
  meeting_id      text not null references meetings(id) on delete cascade,
  text            text not null,
  assignee_id     text,
  anchor_ms       integer not null,
  segment_id      text,
  done            boolean not null default false,
  user_generated  boolean not null default false,
  due_hint        text,
  idx             integer not null
);
create index if not exists actions_meeting on action_items(meeting_id, idx);

-- The evidence ledger for a meeting, kept whole rather than recomputed. It is
-- a record of what happened on one model run, so regenerating it later from
-- different output would be a lie about the past.
create table if not exists evidence (
  meeting_id      text primary key references meetings(id) on delete cascade,
  model           text not null,
  segment_count   integer not null default 0,
  max_idx         integer not null default 0,
  proposed        integer not null default 0,
  resolved        integer not null default 0,
  elapsed_ms      integer not null default 0,
  dropped         jsonb not null default '[]'::jsonb
);

create table if not exists highlights (
  id              text primary key,
  meeting_id      text not null references meetings(id) on delete cascade,
  category_key    text not null,
  start_ms        integer not null,
  end_ms          integer not null,
  title           text not null,
  note            text,
  created_by      text not null default 'you',
  created_at      timestamptz not null default now()
);
create index if not exists highlights_meeting on highlights(meeting_id);

-- Ask threads persist, which is the thing Fathom's own docs say theirs do not.
create table if not exists ask_threads (
  id              text primary key,
  meeting_id      text references meetings(id) on delete cascade,
  title           text not null,
  created_at      timestamptz not null default now()
);

create table if not exists ask_messages (
  id              text primary key,
  thread_id       text not null references ask_threads(id) on delete cascade,
  role            text not null,
  text            text not null,
  -- [{segmentId, anchorMs, snippet, speakerName}] — every one validated
  -- against the segments table before the answer is stored.
  citations       jsonb not null default '[]'::jsonb,
  model           text,
  created_at      timestamptz not null default now(),
  idx             integer not null
);
create index if not exists ask_messages_thread on ask_messages(thread_id, idx);
