import Link from "next/link";
import { corpus } from "@/lib/data/store";
import { PageHeader } from "@/components/page-header";

export const metadata = {
  title: "What's real and what isn't — Fathom Rebuild",
};

export default function AboutPage() {
  const c = corpus();
  const hero = c.byMeeting.get("m-roadmap-lock")!;

  return (
    <div className="mx-auto w-full max-w-[760px] px-4 pb-24 md:px-8">
      <PageHeader
        title="What's real and what isn't"
        subtitle="A rebuild of Fathom, built in a day. This page is the honest accounting."
      />

      <div className="flex flex-col gap-6 text-[14px] leading-[1.68]" style={{ color: "var(--ink-2)" }}>
        <Section title="Simulated">
          <ul className="flex flex-col gap-2">
            <Li label="The recording bot">
              Nothing joins a meeting and nothing captures audio. The brief said stubbing this was a
              legitimate call, and it is where a whole day would have gone. The{" "}
              <Link href="/live" className="underline" style={{ color: "var(--accent-ink)" }}>
                live page
              </Link>{" "}
              streams a real transcript against a clock at 8× so the mid-call interactions are still
              demonstrable rather than described.
            </Li>
            <Li label="Playback">
              There is no video or audio file. The player is a clock running over the transcript&rsquo;s
              own timeline. Everything downstream — the active line, the chapter, the scrubber, the
              speaker lanes — reads from that clock exactly as it would from a media element.
            </Li>
            <Li label="The meetings">
              Nine meetings, {c.segments.length.toLocaleString()} spoken lines, all written for this
              build. They are fiction, but they are internally consistent fiction: the Salesforce
              date promised in the Kestrel call is the one walked back in the roadmap call, and the
              escalation Helen delivers is the one read aloud a week later. Search is only worth
              building if the corpus has threads running through it.
            </Li>
            <Li label="The calendar connection">
              No OAuth, no Google API — the &ldquo;connected&rdquo; state is seeded. What is real is
              the part that matters: the per-meeting capture decision on the meetings list, made
              before the meeting happens, with the rule that chose it stated in words rather than
              applied invisibly. That control is what stops a notetaker turning up where it was not
              wanted, which is one of the sharper complaints in Fathom&rsquo;s reviews.
            </Li>
            <Li label="Summaries and chapters, on the seeded meetings only">
              Authored alongside the nine demo transcripts rather than generated at runtime, so the
              interface is reviewable in thirty seconds without anyone uploading an hour of audio
              first. The structure is the real claim here: each bullet is a row carrying its own
              anchor, which is what makes citations clickable data rather than links buried in
              prose. Bring your own transcript to{" "}
              <Link href="/import" className="underline" style={{ color: "var(--accent-ink)" }}>
                import
              </Link>{" "}
              and all of it is generated by a model instead.
            </Li>
          </ul>
        </Section>

        <Section title="Real">
          <ul className="flex flex-col gap-2">
            <Li label="The analysis, on a transcript you bring">
              <Link href="/import" className="underline" style={{ color: "var(--accent-ink)" }}>
                Import
              </Link>{" "}
              a VTT, SRT or plain transcript and Claude reads it: title, chapters, a templated
              summary, action items and clips, none of it written by hand. The rule the whole layer
              is built on is that <strong>the model never emits a timestamp</strong>. It sees the
              transcript as numbered lines and must cite by index, and the server checks every index
              against the real array before anything reaches the screen.
            </Li>
            <Li label="The evidence panel">
              A claim citing a line that does not exist is <em>dropped, never repaired</em> —
              guessing the nearest plausible line gives you a citation that looks right and points
              at the wrong words. The Evidence tab on an imported meeting shows that happening:
              claims proposed, claims anchored, claims discarded, with the discarded ones quoted
              struck through and the index the model invented. The Evidence toggle on any summary
              puts the actual transcript line underneath every bullet.
            </Li>
            <Li label="Ask">
              Grounded question answering. Retrieval narrows the transcript, the model only ever
              sees real lines, and every citation it returns is validated before you see it — a
              hallucinated index is discarded and an answer that loses all of its citations is
              labelled unsupported rather than presented as fact. Without an API key configured, Ask
              falls back to local retrieval over the transcript and the summary, and says so.
            </Li>
            <Li label="Search">
              BM25 plus TF-IDF cosine similarity with curated query expansion, blended and
              normalised, running over every line and every summary bullet. The ranking, the
              highlighting and the score breakdown on each result are all genuine. The blend slider
              really re-ranks.{" "}
              <em>
                The caveat: the &ldquo;meaning&rdquo; half is sparse retrieval with a synonym table,
                not neural embeddings.
              </em>{" "}
              It solves the vocabulary-mismatch problem Fathom&rsquo;s users complain about. It will
              not solve true paraphrase.
            </Li>
            <Li label="Speaker repair">
              Fully working, and it back-propagates — correct one line or every line attributed to
              that voice. This is the answer to the best-evidenced complaint about the original.
            </Li>
            <Li label="Clips and sharing">
              Real. Cut a range from the transcript, get a link, open it signed-out in a private
              window. A clip link ships only the clip&rsquo;s segments — the rest of the call is
              never sent to that browser.
            </Li>
            <Li label="Export">
              Markdown, WebVTT, SubRip and JSON, generated client-side. Fathom has no transcript
              export at all; clipboard copy is the only route out.
            </Li>
            <Li label="Everything you change">
              Ticking an action item, cutting a clip, fixing a speaker, asking a question — all
              persist across reloads.
            </Li>
          </ul>
        </Section>

        <Section title="Why the demo workspace has no database">
          <p>
            The nine demo meetings are server-rendered from a deterministic seed; everything you
            change — here and on imported meetings — is kept in your own browser and merged over
            it. That is a deliberate choice rather than a corner cut, for three reasons.
          </p>
          <p className="mt-2">
            A shared mutable demo is a demo where the third reviewer sees whatever the second one
            broke. Per-viewer state means everyone gets the workspace as intended, while their own
            changes still survive a refresh — which is what &ldquo;does this feel real&rdquo;
            actually requires. And it removes a credential and a cold start from the path between a
            reviewer and a working link.
          </p>
          <p className="mt-2">
            The honest cost: two people do not see each other&rsquo;s edits. Share links carry their
            payload in the URL precisely so that sharing still crosses the browser boundary — which
            also means the scope on a share link is honoured by the interface, not enforced by a
            server. With accounts, it would be. An imported transcript lives only in the browser
            that imported it, which is why its link will not open anywhere else. The Postgres path
            for exactly this is in the repository under <code>src/lib/pipeline</code>; wiring it up
            is a connection string, not a rewrite.
          </p>
        </Section>

        <Section title="What was deliberately left out">
          <p>
            CRM sync, deal pipelines, coaching scorecards, real calendar OAuth, authentication,
            billing, third-party integrations, mobile, admin. Some of it is Fathom&rsquo;s actual moat, and all
            of it is downstream of the core loop working. Building a shallow version of any of it
            would have shown less judgement than not building it.{" "}
            <code>PRODUCT-NOTES.md</code> in the repository has the full reasoning, the research
            each decision came from, and a ranked table of where the original is weak with how
            confident I am about each one.
          </p>
        </Section>

        <Section title="The case this was built for">
          <p>
            The brief pointed at the eight-person call that runs an hour, because that is where the
            product actually gets tested. That call is{" "}
            <Link
              href="/m/m-roadmap-lock"
              className="underline"
              style={{ color: "var(--accent-ink)" }}
            >
              the roadmap lock
            </Link>{" "}
            — {Math.round(hero.meeting.durationMs / 60000)} minutes, {hero.segments.length} lines,{" "}
            {hero.chapters.length} chapters, eight speakers and one who never says a word. It is
            written to be hostile: overlapping speech, jargon the transcriber fumbles, a late
            joiner, and a decision that gets made, re-opened and re-made.
          </p>
          <p className="mt-2">
            The chapter rail, the speaker-lane minimap, the confidence filter and the repair flow
            all exist because of that call. On a two-person sales call none of them earn their
            place.
          </p>
        </Section>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section
      className="rounded-[var(--radius-lg)] p-5"
      style={{ background: "var(--surface)", border: "1px solid var(--line)" }}
    >
      <h2 className="mb-2.5 text-[15px] font-semibold" style={{ color: "var(--ink)" }}>
        {title}
      </h2>
      {children}
    </section>
  );
}

function Li({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <li className="flex flex-col">
      <span className="text-[13px] font-semibold" style={{ color: "var(--ink)" }}>
        {label}
      </span>
      <span className="text-[13.5px] leading-[1.65]">{children}</span>
    </li>
  );
}
