import type {
  ActionItem,
  Chapter,
  Highlight,
  Meeting,
  MeetingKind,
  Participant,
  Platform,
  Segment,
  Summary,
  SummarySection,
  TemplateKey,
} from "@/lib/types";
import { CONFIDENCE_THRESHOLD } from "@/lib/types";

// ---------------------------------------------------------------------------
// Authoring format
//
// Writing 60 minutes of eight-person dialogue line by line would be mostly
// filler, and filler written by hand is worse than filler generated by rule.
// So the substance is authored — every line that carries a decision, an
// objection, a number or a joke is written out — and the connective tissue
// (back-channel, timing, overlap, ASR confidence) is derived.
//
// The result is a transcript with real density and real shape: long stretches
// where one person explains something, short bursts where four people talk at
// once, and quiet where someone is sharing their screen.
// ---------------------------------------------------------------------------

export interface LineOpts {
  /** Overlaps the previous line. Marks both as crosstalk and dents confidence. */
  over?: boolean;
  /** Silence in seconds before this line. Screen shares, thinking, dead air. */
  gap?: number;
  /** Force low ASR confidence — accents, jargon, someone on a bad connection. */
  shaky?: boolean;
  /** Suppress the automatic back-channel that might follow this line. */
  noBc?: boolean;
}

export type Line = [speaker: string, text: string, opts?: LineOpts];

export interface Scene {
  title: string;
  gist: string;
  lines: Line[];
}

export interface MeetingSpec {
  id: string;
  title: string;
  kind: MeetingKind;
  platform: Platform;
  startedAt: string;
  recordedById: string;
  gist: string;
  /** People on the invite who never spoke. They still show in the roster. */
  silent?: string[];
  scenes: Scene[];
  summaries: Record<string, SummarySectionSpec[]>;
  actionItems: ActionSpec[];
  highlights: HighlightSpec[];
}

export interface SummarySectionSpec {
  heading: string;
  /** [text, anchor phrase or ms, optional speaker] */
  bullets: [string, string | number, string?][];
}

export interface ActionSpec {
  text: string;
  assignee: string | null;
  anchor: string | number;
  done?: boolean;
  userGenerated?: boolean;
  dueHint?: string;
}

export interface HighlightSpec {
  category: string;
  title: string;
  /** Anchor phrase that starts the clip. */
  from: string | number;
  /** How many seconds long. */
  seconds: number;
  note?: string;
  by: string;
}

// Speech rate. 2.3 words/sec is conversational English with the hesitation,
// self-correction and mid-sentence restarts that real speech has — slower than
// read-aloud (3.1) and slower than a prepared presentation (2.6). Big calls run
// slower still because people unmute before they start.
const WORDS_PER_SEC = 2.3;
const MIN_SEGMENT_MS = 900;

const BACK_CHANNEL = [
  "Yeah.",
  "Right.",
  "Mm-hm.",
  "Sure.",
  "Makes sense.",
  "Okay.",
  "Got it.",
  "Exactly.",
  "Yep.",
  "That's fair.",
];

/** Deterministic PRNG so the seed is byte-identical on every build. */
function mulberry32(seed: number) {
  let a = seed >>> 0;
  return function () {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function hashSeed(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

function wordCount(text: string): number {
  return text.trim().split(/\s+/).filter(Boolean).length;
}

function durationFor(text: string): number {
  const words = wordCount(text);
  return Math.max(MIN_SEGMENT_MS, Math.round((words / WORDS_PER_SEC) * 1000));
}

export interface BuiltMeeting {
  meeting: Meeting;
  segments: Segment[];
  chapters: Chapter[];
  summaries: Summary[];
  actionItems: ActionItem[];
  highlights: Highlight[];
}

export function buildMeeting(spec: MeetingSpec): BuiltMeeting {
  const rand = mulberry32(hashSeed(spec.id));
  const segments: Segment[] = [];
  const chapters: Chapter[] = [];

  let t = 0;
  let segN = 0;
  let prevSpeaker = "";

  for (const [sceneIdx, scene] of spec.scenes.entries()) {
    const chapterStart = t;

    for (const [speaker, text, opts] of scene.lines) {
      const o = opts ?? {};

      // Gap before the line: explicit, or a natural beat between turns.
      if (o.gap != null) {
        t += Math.round(o.gap * 1000);
      } else if (segments.length) {
        // Turn-taking gap. Longer on big calls: people unmute, defer to each
        // other, and misjudge whose turn it is.
        const turnGap = 260 + rand() * 900;
        t += o.over ? -Math.round(400 + rand() * 900) : Math.round(turnGap);
      }
      if (t < 0) t = 0;

      const dur = durationFor(text);

      // Confidence model. Crosstalk and flagged lines degrade; otherwise the
      // ASR is good but not perfect, and gets marginally worse the longer the
      // line runs (more chance of one fumbled word).
      let confidence: number;
      if (o.shaky) {
        confidence = 0.58 + rand() * 0.2;
      } else if (o.over) {
        confidence = 0.66 + rand() * 0.2;
      } else {
        confidence = 0.9 + rand() * 0.098 - Math.min(0.06, dur / 400000);
      }

      segments.push({
        id: `${spec.id}-s${segN++}`,
        meetingId: spec.id,
        speakerId: speaker,
        startMs: t,
        endMs: t + dur,
        text,
        confidence: Math.round(confidence * 1000) / 1000,
        crosstalk: o.over || undefined,
      });

      t += dur;

      // Back-channel: someone else murmurs agreement. Only after a decent
      // stretch from one person, never twice in a row, never after crosstalk.
      const others = sceneSpeakers(scene).filter(
        (s) => s !== speaker && s !== prevSpeaker,
      );
      if (
        !o.noBc &&
        !o.over &&
        dur > 7000 &&
        others.length > 1 &&
        rand() < 0.26
      ) {
        const who = others[Math.floor(rand() * others.length)];
        const bc = BACK_CHANNEL[Math.floor(rand() * BACK_CHANNEL.length)];
        t += Math.round(150 + rand() * 350);
        const bcDur = Math.max(700, durationFor(bc));
        segments.push({
          id: `${spec.id}-s${segN++}`,
          meetingId: spec.id,
          speakerId: who,
          startMs: t,
          endMs: t + bcDur,
          text: bc,
          confidence: Math.round((0.93 + rand() * 0.06) * 1000) / 1000,
        });
        t += bcDur;
      }

      prevSpeaker = speaker;
    }

    chapters.push({
      id: `${spec.id}-c${sceneIdx}`,
      meetingId: spec.id,
      startMs: chapterStart,
      endMs: t,
      title: scene.title,
      gist: scene.gist,
    });

    // Beat between topics — someone pulls up a different tab, the next person
    // finds their notes. Longer than a turn-taking gap.
    t += Math.round(2600 + rand() * 4200);
  }

  const durationMs = t;

  // ---- anchor resolution -------------------------------------------------
  // Specs reference moments by a phrase from the transcript rather than a
  // number, so editing dialogue never silently detaches a citation. A phrase
  // that no longer matches throws at build time instead of pointing at 0:00.
  const resolve = (anchor: string | number, ctx: string): number => {
    if (typeof anchor === "number") return anchor;
    const needle = anchor.toLowerCase();
    const hit = segments.find((s) => s.text.toLowerCase().includes(needle));
    if (!hit) {
      throw new Error(
        `[${spec.id}] ${ctx}: anchor phrase not found in transcript: "${anchor}"`,
      );
    }
    return hit.startMs;
  };

  const speakerAt = (ms: number): string =>
    segments.find((s) => s.startMs <= ms && s.endMs >= ms)?.speakerId ?? "";

  // ---- participants ------------------------------------------------------
  const spoke = new Set(segments.map((s) => s.speakerId));
  const roster = [...spoke, ...(spec.silent ?? [])];

  const participants: Participant[] = roster.map((personId) => {
    const mine = segments.filter((s) => s.speakerId === personId);
    let longest = 0;
    let run = 0;
    let prev = "";
    for (const s of segments) {
      if (s.speakerId === personId) {
        run = prev === personId ? run + (s.endMs - s.startMs) : s.endMs - s.startMs;
        longest = Math.max(longest, run);
      }
      prev = s.speakerId;
    }
    return {
      personId,
      talkMs: mine.reduce((a, s) => a + (s.endMs - s.startMs), 0),
      longestMonologueMs: longest,
      wordCount: mine.reduce((a, s) => a + wordCount(s.text), 0),
      questionsAsked: mine.filter((s) => s.text.includes("?")).length,
      attended: spoke.has(personId),
    };
  });

  const lowConf = segments.filter((s) => s.confidence < CONFIDENCE_THRESHOLD).length;

  const meeting: Meeting = {
    id: spec.id,
    title: spec.title,
    kind: spec.kind,
    platform: spec.platform,
    startedAt: spec.startedAt,
    durationMs,
    recordedById: spec.recordedById,
    participants,
    gist: spec.gist,
    hasExternal: false, // filled in by the caller, which knows the roster
    lowConfidenceRatio: segments.length ? lowConf / segments.length : 0,
  };

  // ---- summaries ---------------------------------------------------------
  const summaries: Summary[] = Object.entries(spec.summaries).map(
    ([templateKey, sectionSpecs]) => {
      const sections: SummarySection[] = sectionSpecs.map((sec, i) => ({
        id: `${spec.id}-${templateKey}-sec${i}`,
        heading: sec.heading,
        bullets: sec.bullets.map(([text, anchor, who], j) => {
          const anchorMs = resolve(anchor, `summary/${templateKey}/${sec.heading}`);
          return {
            id: `${spec.id}-${templateKey}-b${i}-${j}`,
            text,
            anchorMs,
            speakerId: who ?? speakerAt(anchorMs),
          };
        }),
      }));
      return {
        id: `${spec.id}-sum-${templateKey}`,
        meetingId: spec.id,
        templateKey: templateKey as TemplateKey,
        generatedAt: new Date(
          new Date(spec.startedAt).getTime() + durationMs + 34_000,
        ).toISOString(),
        sections,
      };
    },
  );

  // ---- action items ------------------------------------------------------
  const actionItems: ActionItem[] = spec.actionItems.map((a, i) => ({
    id: `${spec.id}-a${i}`,
    meetingId: spec.id,
    text: a.text,
    assigneeId: a.assignee,
    anchorMs: resolve(a.anchor, `action/${i}`),
    done: a.done ?? false,
    userGenerated: a.userGenerated ?? false,
    dueHint: a.dueHint,
  }));

  // ---- highlights --------------------------------------------------------
  const highlights: Highlight[] = spec.highlights.map((h, i) => {
    const startMs = resolve(h.from, `highlight/${i}`);
    return {
      id: `${spec.id}-h${i}`,
      meetingId: spec.id,
      categoryKey: h.category,
      startMs,
      endMs: Math.min(durationMs, startMs + h.seconds * 1000),
      title: h.title,
      note: h.note,
      createdById: h.by,
      createdAt: new Date(
        new Date(spec.startedAt).getTime() + durationMs + 600_000 + i * 90_000,
      ).toISOString(),
    };
  });

  return { meeting, segments, chapters, summaries, actionItems, highlights };
}

function sceneSpeakers(scene: Scene): string[] {
  return [...new Set(scene.lines.map((l) => l[0]))];
}
