import type { RawSegment } from "./transcribe";

// Transcript parsing.
//
// Deepgram is unreachable from the environment this was built in, so the way
// a real transcript gets into the product is that you bring one: a VTT or SRT
// file out of Zoom, Meet, Teams, Otter, Whisper — all of which export these —
// or plain "Name: text" lines pasted in.
//
// This is a smaller claim than "we transcribe your audio" and it is made
// plainly in the UI. What matters is that everything downstream — chapters,
// summary, action items, citations — is then generated by a model reading
// YOUR words, not mine.

export interface ParsedTranscript {
  segments: RawSegment[];
  speakerNames: Record<number, string>;
  format: "vtt" | "srt" | "labelled" | "plain";
  warnings: string[];
}

const TIME =
  /(\d{1,2}):(\d{2}):(\d{2})[.,](\d{1,3})|(\d{1,2}):(\d{2})[.,](\d{1,3})/;

function toMs(stamp: string): number | null {
  const m = stamp.trim().match(TIME);
  if (!m) return null;
  if (m[1] !== undefined) {
    return (
      Number(m[1]) * 3600000 + Number(m[2]) * 60000 + Number(m[3]) * 1000 +
      Number(m[4].padEnd(3, "0"))
    );
  }
  return Number(m[5]) * 60000 + Number(m[6]) * 1000 + Number(m[7].padEnd(3, "0"));
}

/** `<v Priya>text` (WebVTT voice span) or `Priya: text`. */
function splitSpeaker(line: string): { name: string | null; text: string } {
  const v = line.match(/^<v\s+([^>]+)>\s*([\s\S]*)$/);
  if (v) return { name: v[1].trim(), text: v[2].replace(/<\/v>\s*$/, "").trim() };

  // A leading "Name:" — but only if it looks like a name, not a sentence that
  // happens to contain a colon.
  const c = line.match(/^([^:]{1,48}):\s+(.*)$/);
  if (c && !/[.?!]/.test(c[1]) && c[1].split(/\s+/).length <= 5) {
    return { name: c[1].trim(), text: c[2].trim() };
  }
  return { name: null, text: line.trim() };
}

export function parseTranscript(input: string): ParsedTranscript {
  const raw = input.replace(/\r\n/g, "\n").trim();
  const warnings: string[] = [];
  if (!raw) return { segments: [], speakerNames: {}, format: "plain", warnings: ["Empty input"] };

  const isVtt = /^WEBVTT/i.test(raw);
  const hasCues = /-->/.test(raw);

  const nameToLabel = new Map<string, number>();
  const labelFor = (name: string | null): number => {
    if (!name) return nameToLabel.size ? 0 : (nameToLabel.set("Speaker 1", 0), 0);
    const key = name.toLowerCase();
    let hit = [...nameToLabel.entries()].find(([k]) => k.toLowerCase() === key);
    if (!hit) {
      const next = nameToLabel.size;
      nameToLabel.set(name, next);
      hit = [name, next];
    }
    return hit[1];
  };

  const segments: RawSegment[] = [];

  if (hasCues) {
    // ---- VTT / SRT --------------------------------------------------------
    const blocks = raw.split(/\n\s*\n/);
    for (const block of blocks) {
      const lines = block.split("\n").filter((l) => l.trim());
      if (!lines.length) continue;
      const cueIdx = lines.findIndex((l) => l.includes("-->"));
      if (cueIdx === -1) continue;

      const [from, to] = lines[cueIdx].split("-->");
      const startMs = toMs(from);
      const endMs = toMs(to ?? "");
      if (startMs === null) continue;

      const body = lines.slice(cueIdx + 1).join(" ").trim();
      if (!body) continue;
      const { name, text } = splitSpeaker(body);
      if (!text) continue;

      segments.push({
        speakerLabel: labelFor(name),
        startMs,
        endMs: endMs ?? startMs + Math.max(1200, text.length * 55),
        text: text.replace(/<[^>]+>/g, "").trim(),
        confidence: 1,
      });
    }
    if (!segments.length) warnings.push("Found cue timings but no readable text.");
  } else {
    // ---- plain or "Name: text" -------------------------------------------
    // No timings, so they are synthesised from speaking rate. Stated in the UI:
    // playback positions are estimated, everything else is real.
    const lines = raw.split("\n").map((l) => l.trim()).filter(Boolean);
    let t = 0;
    for (const line of lines) {
      // Drop a leading bare timestamp like "[00:12]" or "00:12".
      const stripped = line.replace(/^\[?\d{1,2}:\d{2}(:\d{2})?\]?\s*/, "");
      const { name, text } = splitSpeaker(stripped);
      if (!text || text.length < 2) continue;
      const words = text.split(/\s+/).length;
      const dur = Math.max(1200, Math.round((words / 2.4) * 1000));
      segments.push({
        speakerLabel: labelFor(name),
        startMs: t,
        endMs: t + dur,
        text,
        confidence: 1,
      });
      t += dur + 350;
    }
    warnings.push(
      "No timings in this file, so playback positions are estimated from speaking rate. The transcript, the analysis and the citations are real.",
    );
  }

  // Overlap → lower confidence, which drives the existing crosstalk markers.
  for (let i = 1; i < segments.length; i++) {
    if (segments[i].startMs < segments[i - 1].endMs - 120) {
      segments[i].confidence = Math.min(segments[i].confidence, 0.74);
    }
  }

  const speakerNames: Record<number, string> = {};
  for (const [name, label] of nameToLabel) speakerNames[label] = name;
  if (!Object.keys(speakerNames).length) speakerNames[0] = "Speaker 1";

  if (segments.length && Object.keys(speakerNames).length === 1) {
    warnings.push(
      "Only one speaker was found. If your file has several, it may not label them — speaker names can be fixed in the transcript afterwards.",
    );
  }

  return {
    segments,
    speakerNames,
    format: isVtt ? "vtt" : hasCues ? "srt" : nameToLabel.size > 1 ? "labelled" : "plain",
    warnings,
  };
}
