"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { getImported, toBundle, type ImportedMeeting } from "@/lib/imported";
import { HIGHLIGHT_CATEGORIES, TEMPLATES } from "@/lib/seed/cast";
import { MeetingView } from "./meeting/view";
import { Badge } from "./ui";

// An imported meeting renders through exactly the same MeetingView as a
// seeded one. That is the point of having kept the domain model separate from
// the data source: the transcript, chapters, citations and clips here came out
// of a model reading a real file, and not one line of the meeting UI had to
// know that.

export function ImportedView({ id }: { id: string }) {
  const [m, setM] = useState<ImportedMeeting | null | undefined>(undefined);

  useEffect(() => {
    setM(getImported(id));
  }, [id]);

  if (m === undefined) {
    return (
      <div className="mx-auto max-w-[760px] px-4 pt-20 text-center text-[13.5px]" style={{ color: "var(--ink-3)" }}>
        Loading…
      </div>
    );
  }

  if (m === null) {
    return (
      <div className="mx-auto max-w-[620px] px-4 pt-20 text-center">
        <h1 className="text-[18px] font-semibold">Not on this browser</h1>
        <p className="mx-auto mt-2 max-w-[46ch] text-[13.5px] leading-relaxed" style={{ color: "var(--ink-3)" }}>
          Imported transcripts are kept in the browser that imported them, not in a database — so
          this link won&rsquo;t open anywhere else. That&rsquo;s a real limitation of this build and
          it&rsquo;s written up on the{" "}
          <Link href="/about" className="underline" style={{ color: "var(--accent-ink)" }}>
            about page
          </Link>
          .
        </p>
        <Link
          href="/import"
          className="mt-4 inline-block rounded-[var(--radius-sm)] px-4 py-[8px] text-[13px] font-semibold"
          style={{ background: "var(--accent)", color: "var(--on-accent)" }}
        >
          Import one
        </Link>
      </div>
    );
  }

  const b = toBundle(m);

  return (
    <>
      <div className="mx-auto w-full max-w-[1480px] px-4 pt-5 md:px-7">
        <div
          className="flex flex-wrap items-center gap-2 rounded-[var(--radius)] px-3 py-2 text-[12px]"
          style={{ background: "var(--ok-soft)", color: "var(--ink-2)" }}
        >
          <Badge tone="ok">Real analysis</Badge>
          <span>
            Chapters, summary, action items and clips below were generated by{" "}
            <strong>{m.analysis.model}</strong> reading this transcript — not written by hand.
            {m.analysis.evidence && (
              <>
                {" "}
                <strong>
                  {m.analysis.evidence.resolved} of {m.analysis.evidence.proposed} claims
                </strong>{" "}
                survived citation checking; the Evidence tab shows the rest.
              </>
            )}
          </span>
          {m.warnings.length > 0 && (
            <span style={{ color: "var(--ink-faint)" }}>· {m.warnings[0]}</span>
          )}
        </div>
      </div>

      <MeetingView
        meeting={b.meeting}
        segments={b.segments}
        chapters={b.chapters}
        summaries={b.summaries}
        actionItems={b.actionItems}
        highlights={b.highlights}
        people={b.people}
        rosterIds={b.people.map((p) => p.id)}
        categories={HIGHLIGHT_CATEGORIES}
        templates={TEMPLATES}
        suggested={[m.templateKey]}
        isLive
        askSegments={m.segments}
        askSpeakerNames={m.speakerNames}
        evidence={m.analysis.evidence}
      />
    </>
  );
}
